export const POST_SPRINT = "POST_SPRINT"
export const POST_SPRINT_SUCCESS = "POST_SPRINT_SUCCESS"
export const POST_SPRINT_FAIL = "POST_SPRINT_FAIL"

export const LIST_SPRINT = "LIST_SPRINT"
export const LIST_SPRINT_SUCCESS = "LIST_SPRINT_SUCCESS"
export const LIST_SPRINT_FAIL = "LIST_SPRINT_FAIL"
