export const POST_MILESTONE = "POST_MILESTONE"
export const POST_MILESTONE_SUCCESS = "POST_MILESTONE_SUCCESS"
export const POST_MILESTONE_FAIL = "POST_MILESTONE_FAIL"


export const GET_MILESTONE = "GET_MILESTONE"
export const GET_MILESTONE_SUCCESS = "GET_MILESTONE_SUCCESS"
export const GET_MILESTONE_FAIL = "GET_MILESTONE_FAIL"

