export const POST_COMMENT = "POST_COMMENT"
export const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS"
export const POST_COMMENT_FAIL = "POST_COMMENT_FAIL"

export const GET_COMMENT = "GET_COMMENT"
export const GET_COMMENT_SUCCESS = "GET_COMMENT_SUCCESS"
export const GET_COMMENT_FAIL = "GET_COMMENT_FAIL"

export const COMMENT_LIKE = "COMMENT_LIKE"
export const COMMENT_LIKE_SUCCESS = "COMMENT_LIKE_SUCCESS"
export const COMMENT_LIKE_FAIL = "COMMENT_LIKE_FAIL"
